import { readFileSync, writeFileSync, mkdirSync, readdirSync, statSync, unlinkSync } from 'node:fs'
import { homedir } from 'node:os'
import { resolve, basename } from 'node:path'
import { effectiveTurnCost, rawTurnTokens, getPricingForModel } from './cost-tracker.js'
import type { TokenUsage } from '../types.js'

const CLAUDITOR_DIR = resolve(homedir(), '.clauditor')
const SESSIONS_DIR = resolve(CLAUDITOR_DIR, 'sessions')
// Keep legacy path for backward compat reads
const LEGACY_SESSION_FILE = resolve(CLAUDITOR_DIR, 'last-session.md')

const MAX_HANDOFF_AGE_MS = 24 * 60 * 60 * 1000 // 24 hours

export interface SessionStateData {
  savedAt: string
  branch: string | null
  turns: number
  tokensPerTurn: number
  wasteFactor: number
  filesModified: string[]
  cwd: string | null
  /** The user's original task/prompt */
  originalTask: string | null
  /** Last 3 user messages (often contain key decisions) */
  recentUserMessages: string[]
  /** Git commits made during the session */
  gitCommits: string[]
  /** Key bash commands and outcomes (tests, builds, deploys) */
  keyCommands: string[]
  /** Files read during the session */
  filesRead: string[]
  /** Last assistant message (often contains next steps / plan) */
  lastAssistantMessage: string | null
}

/**
 * Encode a cwd path into a safe directory name.
 */
function encodeCwd(cwd: string): string {
  return cwd.replace(/[^a-zA-Z0-9]/g, '-').replace(/-+/g, '-').slice(0, 100)
}

/**
 * Get the sessions directory for a given cwd.
 */
function getSessionsDir(cwd: string | null): string {
  if (!cwd) return SESSIONS_DIR
  return resolve(SESSIONS_DIR, encodeCwd(cwd))
}

/**
 * Save session state to ~/.clauditor/sessions/<encoded-cwd>/<timestamp>.md
 * Each save creates a new file. SessionStart reads recent files and presents choice if multiple.
 */
export function saveSessionState(data: SessionStateData): void {
  try {
    const dir = getSessionsDir(data.cwd)
    mkdirSync(dir, { recursive: true })

    const filesList = data.filesModified.length > 0
      ? data.filesModified.slice(0, 15).join(', ')
      : 'none tracked'

    const sections: string[] = [
      `# Last Session (saved by clauditor)`,
      ``,
      `- **Saved at:** ${data.savedAt}`,
      `- **Branch:** ${data.branch || 'unknown'}`,
      `- **Project:** ${data.cwd || 'unknown'}`,
      `- **Session size:** ${data.turns} turns, ${data.tokensPerTurn}k tokens/turn`,
      `- **Waste factor:** ${data.wasteFactor}x`,
      `- **Files modified:** ${filesList}`,
    ]

    if (data.filesRead && data.filesRead.length > 0) {
      sections.push(`- **Files read:** ${data.filesRead.slice(0, 15).join(', ')}`)
    }

    if (data.originalTask) {
      sections.push(``, `## Original Task`, data.originalTask)
    }

    if (data.gitCommits && data.gitCommits.length > 0) {
      sections.push(``, `## Commits Made`)
      for (const commit of data.gitCommits.slice(0, 10)) {
        sections.push(`- ${commit}`)
      }
    }

    if (data.keyCommands && data.keyCommands.length > 0) {
      sections.push(``, `## Key Commands & Results`)
      for (const cmd of data.keyCommands.slice(0, 10)) {
        sections.push(`- ${cmd}`)
      }
    }

    if (data.recentUserMessages && data.recentUserMessages.length > 0) {
      sections.push(``, `## Recent User Messages`)
      for (const msg of data.recentUserMessages) {
        sections.push(`> ${msg}`)
      }
    }

    if (data.lastAssistantMessage) {
      sections.push(``, `## Where We Left Off`, data.lastAssistantMessage)
    }

    sections.push(``)

    const timestamp = Date.now()
    const filePath = resolve(dir, `${timestamp}.md`)
    writeFileSync(filePath, sections.join('\n'))

    // Also write to legacy path for backward compat
    writeFileSync(LEGACY_SESSION_FILE, sections.join('\n'))
  } catch (err) {
    process.stderr.write(`clauditor: failed to save session state: ${err}\n`)
  }
}

/**
 * Save a PostCompact summary (Claude's own LLM-generated summary) per-session.
 *
 * Merges Claude's prose with mechanically extracted structured state.
 * Research (Size-Fidelity Paradox, arxiv 2602.09789) shows LLM summaries
 * lose commits, commands, and conditional info. The mechanical data fills
 * those gaps. Claude's prose adds reasoning and context the transcript can't.
 */
export async function savePostCompactSummary(
  summary: string,
  cwd: string | null,
  transcriptPath?: string | null
): Promise<void> {
  try {
    const dir = getSessionsDir(cwd)
    mkdirSync(dir, { recursive: true })

    const sections: string[] = [
      `# Last Session (saved by clauditor via PostCompact)`,
      ``,
      `> This summary was generated by Claude while it still had full context.`,
    ]

    // Merge mechanical state if transcript is available
    if (transcriptPath) {
      try {
        const state = extractSessionStateFromTranscript('postcompact', transcriptPath)
        if (state) {
          sections.push(``)

          if (state.branch) sections.push(`- **Branch:** ${state.branch}`)
          if (state.cwd) sections.push(`- **Project:** ${state.cwd}`)
          sections.push(`- **Session size:** ${state.turns} turns, ${state.tokensPerTurn}k tokens/turn`)

          if (state.filesModified.length > 0) {
            sections.push(`- **Files modified:** ${state.filesModified.slice(0, 20).join(', ')}`)
          }

          if (state.gitCommits.length > 0) {
            sections.push(``, `## Commits Made`)
            for (const c of state.gitCommits.slice(0, 10)) {
              sections.push(`- ${c}`)
            }
          }

          if (state.keyCommands.length > 0) {
            sections.push(``, `## Key Commands & Results`)
            for (const c of state.keyCommands.slice(0, 10)) {
              sections.push(`- ${c}`)
            }
          }
        }
      } catch {
        // Non-critical — mechanical extraction failed, Claude's prose is still valuable
      }
    }

    // Parse Claude's structured handoff sections (if it followed the template)
    // Falls back to raw prose if template wasn't followed
    const parsed = parseStructuredHandoff(summary)

    if (parsed.isStructured) {
      if (parsed.task) sections.push(``, `## Task`, parsed.task)
      if (parsed.completed.length > 0) {
        sections.push(``, `## Completed`)
        for (const item of parsed.completed) sections.push(`- ${item}`)
      }
      if (parsed.inProgress.length > 0) {
        sections.push(``, `## In Progress`)
        for (const item of parsed.inProgress) sections.push(`- ${item}`)
      }
      if (parsed.failedApproaches.length > 0) {
        sections.push(``, `## Failed Approaches`)
        for (const item of parsed.failedApproaches) sections.push(`- ${item}`)
      }
      if (parsed.dependencies.length > 0) {
        sections.push(``, `## Dependencies`)
        for (const item of parsed.dependencies) sections.push(`- ${item}`)
      }
      if (parsed.decisions.length > 0) {
        sections.push(``, `## Decisions`)
        for (const item of parsed.decisions) sections.push(`- ${item}`)
      }
      if (parsed.userPreferences.length > 0) {
        sections.push(``, `## User Preferences`)
        for (const item of parsed.userPreferences) sections.push(`- ${item}`)
      }
      if (parsed.blockers.length > 0) {
        sections.push(``, `## Blockers`)
        for (const item of parsed.blockers) sections.push(`- ${item}`)
      }
      if (parsed.remainder) {
        sections.push(``, `## Additional Context`, parsed.remainder)
      }
    } else {
      // Unstructured — use Claude's prose as-is
      sections.push(``, `## Session Summary`, ``, summary.trim())
    }

    sections.push(``)

    const content = sections.join('\n')

    // Score the handoff quality if transcript is available
    if (transcriptPath) {
      try {
        const { extractFacts, scoreHandoff } = await import('./handoff-quality.js')
        const facts = extractFacts(transcriptPath)
        if (facts.length > 0) {
          const score = scoreHandoff(facts, content)
          const pct = Math.round(score.score * 100)
          sections.push(``, `---`, `*Handoff quality: ${pct}% information preserved (${score.preservedFacts}/${score.totalFacts} facts)*`)

          // Log for activity tracking
          const { logActivity } = await import('./activity-log.js')
          logActivity({
            type: 'notification',
            session: 'handoff',
            message: `Handoff quality: ${pct}% preserved (${score.preservedFacts}/${score.totalFacts} facts)`,
          }).catch(() => {})
        }
      } catch {
        // Non-critical — scoring failed
      }
    }

    const finalContent = sections.join('\n')
    const timestamp = Date.now()
    writeFileSync(resolve(dir, `${timestamp}.md`), finalContent)
    writeFileSync(LEGACY_SESSION_FILE, finalContent)
  } catch (err) {
    process.stderr.write(`clauditor: failed to save PostCompact summary: ${err}\n`)
  }
}

export interface HandoffFile {
  path: string
  content: string
  timestamp: number
  isPostCompact: boolean
  /** Project path extracted from handoff content (e.g. "/Users/.../my-project") */
  project: string | null
}

/**
 * Extract a human-readable one-line description from a handoff file.
 * Tries multiple strategies depending on the content format.
 */
export function extractHandoffDescription(handoff: HandoffFile): string {
  const lines = handoff.content.split('\n')

  // PostCompact: look for first meaningful line after <analysis> or after the header
  if (handoff.isPostCompact) {
    for (const line of lines) {
      const trimmed = line.trim()
      // Skip headers, empty lines, blockquotes, and tags
      if (!trimmed) continue
      if (trimmed.startsWith('#')) continue
      if (trimmed.startsWith('>')) continue
      if (trimmed.startsWith('<')) continue
      // Found a meaningful line — extract key info
      // Often starts with "1." or "- " or "Let me" or "User asked"
      const clean = trimmed.replace(/^\d+\.\s*\*\*[^*]+\*\*:?\s*/, '').replace(/^\*\*[^*]+\*\*:?\s*/, '')
      if (clean.length > 10) return clean.slice(0, 100)
    }
  }

  // Mechanical: build from branch + original task or where we left off
  const branch = lines.find(l => l.startsWith('- **Branch:**'))?.replace('- **Branch:** ', '') || null

  // Look for "## Where We Left Off" content
  const woIdx = lines.findIndex(l => l.startsWith('## Where We Left Off'))
  if (woIdx >= 0 && lines[woIdx + 1]?.trim()) {
    const leftOff = lines[woIdx + 1].trim().slice(0, 80)
    if (leftOff.length > 10 && !leftOff.startsWith('<') && !leftOff.startsWith('[Request')) {
      return branch ? `${branch} — ${leftOff}` : leftOff
    }
  }

  // Look for "## Original Task" content
  const taskIdx = lines.findIndex(l => l.startsWith('## Original Task'))
  if (taskIdx >= 0 && lines[taskIdx + 1]?.trim()) {
    const task = lines[taskIdx + 1].trim().slice(0, 80)
    if (task.length > 10 && !task.startsWith('<') && !task.startsWith('[Request')) {
      return branch ? `${branch} — ${task}` : task
    }
  }

  // Look for recent user messages
  const msgIdx = lines.findIndex(l => l.startsWith('## Recent User Messages'))
  if (msgIdx >= 0) {
    for (let i = msgIdx + 1; i < lines.length && i < msgIdx + 4; i++) {
      const msg = lines[i]?.replace(/^>\s*/, '').trim()
      if (msg && msg.length > 10 && !msg.startsWith('<') && !msg.startsWith('[Request')) {
        return branch ? `${branch} — ${msg.slice(0, 80)}` : msg.slice(0, 80)
      }
    }
  }

  // Fallback: branch + session size
  const sizeLine = lines.find(l => l.startsWith('- **Session size:**'))?.replace('- **Session size:** ', '')
  if (branch) return sizeLine ? `${branch} (${sizeLine})` : branch

  return handoff.isPostCompact ? 'Claude-generated summary' : 'Session snapshot'
}

/**
 * Read recent handoff files across ALL projects (last 24 hours).
 * Scans every subdirectory under ~/.clauditor/sessions/ so that
 * cross-project handoffs are always visible.
 * Returns them sorted by timestamp, most recent first.
 */
export function readRecentHandoffs(cwd?: string | null): HandoffFile[] {
  const results: HandoffFile[] = []
  const cutoff = Date.now() - MAX_HANDOFF_AGE_MS

  // If cwd is provided, only scan that project's directory
  const dirsToScan: string[] = []
  if (cwd) {
    const projectDir = resolve(SESSIONS_DIR, encodeCwd(cwd))
    dirsToScan.push(projectDir)
  } else {
    // Scan all project subdirectories under SESSIONS_DIR
    try {
      const entries = readdirSync(SESSIONS_DIR, { withFileTypes: true })
      for (const entry of entries) {
        if (entry.isDirectory()) {
          dirsToScan.push(resolve(SESSIONS_DIR, entry.name))
        }
      }
    } catch {
      // Sessions dir doesn't exist yet
    }
    // Also scan the root sessions dir (for files saved without cwd)
    dirsToScan.push(SESSIONS_DIR)
  }

  for (const dir of dirsToScan) {
    try {
      const files = readdirSync(dir).filter(f => f.endsWith('.md'))
      for (const file of files) {
        const filePath = resolve(dir, file)
        try {
          const fileTs = parseInt(basename(file, '.md'), 10)
          const st = statSync(filePath)
          const effectiveTs = isNaN(fileTs) ? st.mtimeMs : fileTs

          if (effectiveTs < cutoff) {
            try { unlinkSync(filePath) } catch {}
            continue
          }
          const content = readFileSync(filePath, 'utf-8')

          // Extract project name from content for labeling
          const projectMatch = content.match(/\*\*Project:\*\*\s*(.+)/)
          const project = projectMatch ? projectMatch[1].trim() : null

          results.push({
            path: filePath,
            content,
            timestamp: effectiveTs,
            isPostCompact: content.includes('PostCompact'),
            project,
          })
        } catch {}
      }
    } catch {}
  }

  // Fallback: check legacy file if nothing found
  if (results.length === 0) {
    try {
      const st = statSync(LEGACY_SESSION_FILE)
      if (st.mtimeMs >= cutoff) {
        const content = readFileSync(LEGACY_SESSION_FILE, 'utf-8')
        results.push({
          path: LEGACY_SESSION_FILE,
          content,
          timestamp: st.mtimeMs,
          isPostCompact: content.includes('PostCompact'),
          project: null,
        })
      }
    } catch {}
  }

  return results.sort((a, b) => b.timestamp - a.timestamp)
}

/**
 * Read the most recent session state. Returns null if nothing saved.
 * For backward compatibility with code that uses the old API.
 */
export function readLastSessionState(): string | null {
  try {
    return readFileSync(LEGACY_SESSION_FILE, 'utf-8')
  } catch {
    return null
  }
}

/**
 * Extract session state data from a JSONL transcript.
 */
export function extractSessionStateFromTranscript(
  sessionId: string,
  transcriptPath: string
): SessionStateData | null {
  try {
    const content = readFileSync(transcriptPath, 'utf-8')
    const lines = content.split('\n')

    let cwd: string | null = null
    let branch: string | null = null
    let turnCount = 0
    const turnTokens: number[] = []
    const turnCosts: number[] = []
    let model: string | null = null
    const filesModified = new Set<string>()
    const filesRead = new Set<string>()
    const gitCommits: string[] = []
    const keyCommands: string[] = []
    const userMessages: string[] = []
    let originalTask: string | null = null
    let lastAssistantMessage: string | null = null

    // Get cwd and branch from most recent user record
    for (let i = lines.length - 1; i >= 0; i--) {
      try {
        const r = JSON.parse(lines[i])
        if (r.type === 'user' && r.cwd) {
          cwd = r.cwd
          branch = r.gitBranch || null
          break
        }
      } catch {}
    }

    // Scan all records
    for (const line of lines) {
      try {
        const r = JSON.parse(line)

        // Extract user messages (skip meta/system messages)
        if (r.type === 'user' && !r.isMeta) {
          const msg = extractUserMessage(r)
          if (msg && !msg.startsWith('<')) {
            userMessages.push(msg)
            if (!originalTask) originalTask = msg
          }
        }

        // Count turns
        if (r.type === 'assistant' && r.message?.usage) {
          const u = r.message.usage
          if (!model && r.message?.model) model = r.message.model
          const usage: TokenUsage = {
            input_tokens: u.input_tokens || 0,
            output_tokens: u.output_tokens || 0,
            cache_creation_input_tokens: u.cache_creation_input_tokens || 0,
            cache_read_input_tokens: u.cache_read_input_tokens || 0,
            cache_creation: u.cache_creation,
          }
          turnTokens.push(rawTurnTokens(usage))
          turnCosts.push(
            effectiveTurnCost(usage, model ? getPricingForModel(model) : undefined)
          )
          turnCount++
        }

        // Extract tool calls + last assistant text
        if (r.type === 'assistant' && r.message?.content) {
          // Capture the last assistant text message (often contains plan/next steps)
          const textBlocks = (r.message.content as Array<{ type: string; text?: string }>)
            .filter((b: { type: string; text?: string }) => b.type === 'text' && b.text)
            .map((b: { type: string; text?: string }) => b.text!)
          if (textBlocks.length > 0) {
            lastAssistantMessage = textBlocks.join('\n').trim()
          }

          for (const block of r.message.content) {
            if (block.type !== 'tool_use') continue

            // Files modified
            if (block.name === 'Edit' || block.name === 'Write') {
              const fp = block.input?.file_path
              if (fp) filesModified.add(fp.split('/').pop() || fp)
            }

            // Files read
            if (block.name === 'Read') {
              const fp = block.input?.file_path
              if (fp) filesRead.add(fp.split('/').pop() || fp)
            }

            // Bash commands — extract git commits, test results, builds
            if (block.name === 'Bash') {
              const cmd = block.input?.command as string | undefined
              if (!cmd) continue

              // Git commits — various formats
              if (cmd.includes('git') && cmd.includes('commit')) {
                let commitMsg: string | null = null

                // HEREDOC format first (most common in Claude Code): -m "$(cat <<'EOF'\nmessage\nEOF\n)"
                if (cmd.includes('<<')) {
                  const heredocMatch = cmd.match(/<<['"]?EOF['"]?\)?\s*\n\s*(.+)/)
                  if (heredocMatch) commitMsg = heredocMatch[1].trim()
                }

                // Standard formats: -m "message" or -m 'message'
                if (!commitMsg) {
                  const match = cmd.match(/-m\s+["']([^"'\n]+)["']/) ||
                    cmd.match(/commit\s+-m\s+"([^"\n]+)"/) ||
                    cmd.match(/commit\s+-m\s+'([^'\n]+)'/)
                  if (match) commitMsg = match[1].trim()
                }

                if (commitMsg) {
                  gitCommits.push(commitMsg.slice(0, 120))
                }
              }

              // Key commands: tests, builds, deploys, installs
              if (/\b(test|build|deploy|lint|format|install|migrate|seed)\b/i.test(cmd)) {
                const shortCmd = cmd.split('\n')[0].slice(0, 100)
                keyCommands.push(shortCmd)
              }
            }
          }
        }

        // Also check tool results in user messages (where Claude Code puts them)
        if (r.type === 'user' && Array.isArray(r.message?.content)) {
          for (const block of r.message.content) {
            if (block.type === 'tool_result' && typeof block.content === 'string') {
              // Check for test results
              if (/passed|failed|error/i.test(block.content) && block.content.length < 200) {
                const resultLine = block.content.split('\n').find(
                  (l: string) => /passed|failed|succeeded|error/i.test(l)
                )
                if (resultLine) {
                  keyCommands.push(`→ ${resultLine.trim().slice(0, 100)}`)
                }
              }
            }
          }
        }
      } catch {}
    }

    if (turnTokens.length < 5) return null

    const current = turnTokens.slice(-5).reduce((a, b) => a + b, 0) / 5
    // Cost ratio, not token ratio - see cost-tracker.effectiveTurnCost.
    const baselineCost = turnCosts.slice(0, 5).reduce((a, b) => a + b, 0) / 5
    const currentCost = turnCosts.slice(-5).reduce((a, b) => a + b, 0) / 5
    const wasteFactor = baselineCost > 0 ? Math.round(currentCost / baselineCost) : 1

    // Deduplicate key commands by base command (strip pipes, redirects, tail/head)
    const seenBases = new Set<string>()
    const uniqueCommands: string[] = []
    for (const cmd of keyCommands) {
      // Normalize: take the command before any pipe/redirect, strip trailing args
      const base = cmd.split(/\s*[|>&]\s*/)[0].trim().split(/\s+/).slice(0, 3).join(' ')
      if (!seenBases.has(base)) {
        seenBases.add(base)
        uniqueCommands.push(cmd)
      }
    }
    const dedupedCommands = uniqueCommands.slice(0, 10)

    // Get last 3 user messages (most recent decisions)
    const recentUserMessages = userMessages
      .slice(-3)
      .map(m => m.slice(0, 200))

    // Truncate original task
    if (originalTask && originalTask.length > 300) {
      originalTask = originalTask.slice(0, 300) + '...'
    }

    return {
      savedAt: new Date().toISOString().slice(0, 16).replace('T', ' '),
      branch,
      turns: turnCount,
      tokensPerTurn: Math.round(current / 1000),
      wasteFactor,
      filesModified: Array.from(filesModified),
      filesRead: Array.from(filesRead),
      cwd,
      originalTask,
      recentUserMessages,
      gitCommits,
      keyCommands: dedupedCommands,
      lastAssistantMessage: lastAssistantMessage ? lastAssistantMessage.slice(0, 500) : null,
    }
  } catch {
    return null
  }
}

// ─── Structured Handoff Parser ──────────────────────────────

interface ParsedHandoff {
  isStructured: boolean
  task: string | null
  completed: string[]
  inProgress: string[]
  failedApproaches: string[]
  dependencies: string[]
  decisions: string[]
  userPreferences: string[]
  blockers: string[]
  whatSurprisedMe: string[]
  gotchas: string[]
  remainder: string | null
}

const SECTION_HEADERS: Record<string, keyof ParsedHandoff> = {
  'TASK:': 'task',
  'COMPLETED:': 'completed',
  'IN_PROGRESS:': 'inProgress',
  'FAILED_APPROACHES:': 'failedApproaches',
  'DEPENDENCIES:': 'dependencies',
  'DECISIONS:': 'decisions',
  'USER_PREFERENCES:': 'userPreferences',
  'BLOCKERS:': 'blockers',
  'WHAT_SURPRISED_ME:': 'whatSurprisedMe',
  'GOTCHAS:': 'gotchas',
}

/**
 * Parse Claude's structured handoff output.
 * If at least 2 recognized sections are found, treat as structured.
 * Otherwise fall back to unstructured prose.
 */
export function parseStructuredHandoff(text: string): ParsedHandoff {
  const result: ParsedHandoff = {
    isStructured: false,
    task: null,
    completed: [],
    inProgress: [],
    failedApproaches: [],
    dependencies: [],
    decisions: [],
    userPreferences: [],
    blockers: [],
    whatSurprisedMe: [],
    gotchas: [],
    remainder: null,
  }

  // Find which sections are present
  const headerEntries = Object.entries(SECTION_HEADERS)
  const foundHeaders = headerEntries.filter(([header]) =>
    text.includes(header)
  )

  // Need at least 2 sections to consider it structured
  if (foundHeaders.length < 2) {
    return result
  }

  result.isStructured = true

  // Split text into sections by header
  const lines = text.split('\n')
  let currentSection: keyof ParsedHandoff | null = null
  const remainderLines: string[] = []

  for (const line of lines) {
    const trimmed = line.trim()

    // Check if this line starts a new section
    const matchedHeader = headerEntries.find(([header]) =>
      trimmed.startsWith(header)
    )

    if (matchedHeader) {
      const [header, field] = matchedHeader
      currentSection = field

      // TASK: is a single-line field — value is on the same line
      if (field === 'task') {
        const value = trimmed.slice(header.length).trim()
        if (value) result.task = value
      }
      continue
    }

    if (!currentSection) {
      // Lines before any section header — or outside sections
      if (trimmed && !trimmed.startsWith('[clauditor') && !trimmed.includes('tokens/turn')) {
        remainderLines.push(trimmed)
      }
      continue
    }

    // Collect bullet items for list sections
    if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
      const item = trimmed.slice(2).trim()
      if (item && currentSection !== 'task') {
        const arr = result[currentSection]
        if (Array.isArray(arr)) {
          arr.push(item)
        }
      }
    } else if (trimmed && currentSection === 'task' && !result.task) {
      result.task = trimmed
    }
  }

  if (remainderLines.length > 0) {
    result.remainder = remainderLines.join('\n').trim() || null
  }

  return result
}

/**
 * Extract the text content from a user record.
 */
function extractUserMessage(record: Record<string, unknown>): string | null {
  const msg = record.message as { content?: unknown } | undefined
  if (!msg?.content) return null

  if (typeof msg.content === 'string') {
    return msg.content.trim() || null
  }

  if (Array.isArray(msg.content)) {
    // Find text blocks, skip tool_result blocks
    const textParts = (msg.content as Array<{ type: string; text?: string }>)
      .filter(b => b.type === 'text' && b.text)
      .map(b => b.text!)
    return textParts.join(' ').trim() || null
  }

  return null
}

/**
 * Find transcript path for a session ID.
 */
export function findTranscriptPathSync(sessionId: string): string | null {
  const projectsDir = resolve(homedir(), '.claude/projects')
  try {
    const dirs = readdirSync(projectsDir, { withFileTypes: true })
    for (const dir of dirs) {
      if (!dir.isDirectory()) continue
      const candidate = resolve(projectsDir, dir.name, `${sessionId}.jsonl`)
      try {
        readFileSync(candidate, { flag: 'r' })
        return candidate
      } catch {}
    }
  } catch {}
  return null
}
